on: [push]

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  role_switcher:
    runs-on: ubuntu-latest
    name: role switcher
    steps:
      - uses: actions/checkout@v3
      - uses: .github/workflows/action.yaml
        with:
          role-for-oidc: 'arn:aws:iam::360884427279:role/github_oidc'
          role-to-assume: 'arn:aws:iam::360884427279:role/external_account'
          aws-region: 'us-east-1'
          role-session-name: 'foobar'
          role-duration-seconds: 120
      - run: echo "foo"
        shell: bash
          
