on: push

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  role_switcher:
    runs-on: ubuntu-latest
    name: role switcher
    steps:
      - uses: actions/checkout@v3 
      - name: assume oidc role
        uses: meisterplan/configure-aws-credentials@v1.6.0-custom
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::360884427279:role/github_oidc'
          role-session-name: 'oidc-role'
          role-duration-seconds: 900
      - name: assume target role
        uses: meisterplan/configure-aws-credentials@v1.6.0-custom
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::360884427279:role/external_account'
          role-session-name: 'external-account-role'
          role-duration-seconds: 900
      - run: echo "foobar" && env
