on: [push]

jobs:
  role_switcher:
    runs-on: ubuntu-latest
    name: role switcher
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github_actions_terraform_role_switching@v1
        with:
          role-for-oidc: 'arn:aws:iam::360884427279:role/github_oidc'
          role-to-assume: 'arn:aws:iam::360884427279:role/external_account'
          aws-region: 'us-east-1'
          role-session-name: 'foobar'
          role-duration-seconds: '120'
        run: echo "foo"
        shell: bash
          
